### ISSUE TITLE
The annotation "@nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleriesAction() does not exist, or could not be auto-loaded.

### ISSUE THREAD

**Issue by arrowb** [sonata-project/SonataMediaBundle#1424] opened 2018-04-27 07:17 UTC
Hi,

I've error

[Semantical Error] The annotation "@nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleriesAction() does not exist, or could not be auto-loaded.

"sonata-project/media-bundle": "^3.10",
"nelmio/api-doc-bundle": "^3.2",
"symfony/symfony": "3.4.*",

**Comment by kunicmarko20** [comment] 2018-04-27 07:25
You are using Nelmio 3.x and we currently support 2.x. Duplicate of https://github.com/sonata-project/SonataMediaBundle/issues/1390, so I will close this.

**Closed by kunicmarko20** 2018-04-27 07:25 UTC
