### ISSUE TITLE
Configuring `twig.form_themes` causes error 'There are no registered paths for namespace "SonataMediaBundle"' with `symfony/*:^4.0`

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataMediaBundle#1415] opened 2018-04-05 18:00 UTC
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.33.0          3.33.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1          3.12.1             Symfony SonataBlockBundle
sonata-project/cache                     2.0.1           2.0.1              Cache library
sonata-project/core-bundle               3.9.1           3.9.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1           2.3.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2           1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.x-dev f097a34 dev-master bfa60ae Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0           2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0           1.8.0              Lightweight Exporter library
sonata-project/intl-bundle               2.4.0           2.4.0              Symfony SonataIntlBundle
sonata-project/media-bundle              3.11.0          3.11.0             Symfony SonataMediaBundle
sonata-project/notification-bundle       3.4.0           3.4.0              Symfony SonataNotificationBundle
sonata-project/user-bundle               4.1.1           4.1.1              Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.0.7  v4.0.7  Symfony Asset Component
symfony/cache                v4.0.7  v4.0.7  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.7  v3.4.7  Symfony ClassLoader Component
symfony/config               v4.0.7  v4.0.7  Symfony Config Component
symfony/console              v4.0.7  v4.0.7  Symfony Console Component
symfony/debug                v4.0.7  v4.0.7  Symfony Debug Component
symfony/debug-bundle         v4.0.7  v4.0.7  Symfony DebugBundle
symfony/debug-pack           v1.0.5  v1.0.5  A debug pack for Symfony projects
symfony/dependency-injection v4.0.7  v4.0.7  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.0.7  v4.0.7  Symfony Doctrine Bridge
symfony/dotenv               v4.0.7  v4.0.7  Registers environment variables from a .env file
symfony/event-dispatcher     v4.0.7  v4.0.7  Symfony EventDispatcher Component
symfony/expression-language  v4.0.7  v4.0.7  Symfony ExpressionLanguage Component
symfony/filesystem           v4.0.7  v4.0.7  Symfony Filesystem Component
symfony/finder               v4.0.7  v4.0.7  Symfony Finder Component
symfony/flex                 v1.0.78 v1.0.78
symfony/form                 v4.0.7  v4.0.7  Symfony Form Component
symfony/framework-bundle     v4.0.7  v4.0.7  Symfony FrameworkBundle
symfony/http-foundation      v4.0.7  v4.0.7  Symfony HttpFoundation Component
symfony/http-kernel          v4.0.7  v4.0.7  Symfony HttpKernel Component
symfony/inflector            v4.0.7  v4.0.7  Symfony Inflector Component
symfony/intl                 v4.0.7  v4.0.7  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle         v1.3.1  v1.3.1  Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge       v4.0.7  v4.0.7  Symfony Monolog Bridge
symfony/monolog-bundle       v3.2.0  v3.2.0  Symfony MonologBundle
symfony/options-resolver     v4.0.7  v4.0.7  Symfony OptionsResolver Component
symfony/orm-pack             v1.0.5  v1.0.5  A pack for the Doctrine ORM
symfony/phpunit-bridge       v4.0.7  v4.0.7  Symfony PHPUnit Bridge
symfony/polyfill-apcu        v1.7.0  v1.7.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu    v1.7.0  v1.7.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.7.0  v1.7.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56       v1.7.0  v1.7.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70       v1.7.0  v1.7.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72       v1.7.0  v1.7.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util        v1.7.0  v1.7.0  Symfony utilities for portability of PHP codes
symfony/process              v4.0.7  v4.0.7  Symfony Process Component
symfony/profiler-pack        v1.0.3  v1.0.3  A pack for the Symfony web profiler
symfony/property-access      v4.0.7  v4.0.7  Symfony PropertyAccess Component
symfony/property-info        v4.0.7  v4.0.7  Symfony Property Info Component
symfony/routing              v4.0.7  v4.0.7  Symfony Routing Component
symfony/security             v4.0.7  v4.0.7  Symfony Security Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.0.7  v4.0.7  Symfony SecurityBundle
symfony/serializer           v4.0.7  v4.0.7  Symfony Serializer Component
symfony/stopwatch            v4.0.7  v4.0.7  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.2  v3.2.2  Symfony SwiftmailerBundle
symfony/templating           v4.0.7  v4.0.7  Symfony Templating Component
symfony/translation          v4.0.7  v4.0.7  Symfony Translation Component
symfony/twig-bridge          v4.0.7  v4.0.7  Symfony Twig Bridge
symfony/twig-bundle          v4.0.7  v4.0.7  Symfony TwigBundle
symfony/validator            v4.0.7  v4.0.7  Symfony Validator Component
symfony/var-dumper           v4.0.7  v4.0.7  Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle  v4.0.7  v4.0.7  Symfony WebProfilerBundle
symfony/web-server-bundle    v4.0.7  v4.0.7  Symfony WebServerBundle
symfony/yaml                 v4.0.7  v4.0.7  Symfony Yaml Component

```

#### PHP version

```
$ php -v
PHP 7.2.2 (cli) (built: Feb  6 2018 22:05:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.18.2~linux-x64-non_zts72, https://blackfire.io, by SensioLabs

```

## Subject

I'm migrating from `symfony/3.x` to `symfony/4.x`, and there is an exception in the admin while trying to render a media type. If I remove `'@SonataMediaBundle/Form/media_widgets.html.twig'` from [`twig.form_themes`](../blob/3.x/docs/reference/form.rst) configuration, the exception just gone.
Obviously, I have "SonataMediaBundle" enabled in `config/bundles.php` and configured in `config/packages/sonata_media.yaml`:
<details>

```
Twig_Error_Loader:
There are no registered paths for namespace "SonataMediaBundle".

  at vendor/sonata-project/admin-bundle/src/Resources/views/CRUD/base_list.html.twig:271
  at Twig_Loader_Filesystem->findTemplate('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/symfony/twig-bundle/Loader/FilesystemLoader.php:76)
  at Symfony\Bundle\TwigBundle\Loader\FilesystemLoader->findTemplate('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/twig/twig/lib/Twig/Loader/Filesystem.php:143)
  at Twig_Loader_Filesystem->getCacheKey('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/twig/twig/lib/Twig/Environment.php:270)
  at Twig_Environment->getTemplateClass('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/twig/twig/lib/Twig/Environment.php:350)
  at Twig_Environment->loadTemplate('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/symfony/twig-bridge/Form/TwigRendererEngine.php:157)
  at Symfony\Bridge\Twig\Form\TwigRendererEngine->loadResourcesFromTheme('_filter_form', '@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/symfony/twig-bridge/Form/TwigRendererEngine.php:111)
  at Symfony\Bridge\Twig\Form\TwigRendererEngine->loadResourceForBlockName('_filter_form', object(FormView), '_filter_errors')
     (vendor/symfony/form/AbstractRendererEngine.php:146)
  at Symfony\Component\Form\AbstractRendererEngine->loadResourceForBlockNameHierarchy('_filter_form', object(FormView), array('form_errors', '_filter_errors'), 1)
     (vendor/symfony/form/AbstractRendererEngine.php:84)
  at Symfony\Component\Form\AbstractRendererEngine->getResourceForBlockNameHierarchy(object(FormView), array('form_errors', '_filter_errors'), 1)
     (vendor/symfony/form/FormRenderer.php:208)
  at Symfony\Component\Form\FormRenderer->searchAndRenderBlock(object(FormView), 'errors')
     (var/cache/local/twig/b4/b41052ac663b03cdf8d7b2ab15f39a53adf1961b584240f149af40840fcc4bb7.php:914)

...
```
</details>

## Steps to reproduce
Configure `twig.form_themes` with '@SonataMediaBundle/Form/media_widgets.html.twig':
```yaml
# config/packages/twig.yaml

twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataMediaBundle/Form/media_widgets.html.twig'
```
## Expected results
n/a
## Actual results

```
Twig_Error_Loader:
There are no registered paths for namespace "SonataMediaBundle".

  at vendor/sonata-project/admin-bundle/src/Resources/views/CRUD/base_list.html.twig:271
  at Twig_Loader_Filesystem->findTemplate('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/symfony/twig-bundle/Loader/FilesystemLoader.php:76)
  at Symfony\Bundle\TwigBundle\Loader\FilesystemLoader->findTemplate('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/twig/twig/lib/Twig/Loader/Filesystem.php:143)
  at Twig_Loader_Filesystem->getCacheKey('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/twig/twig/lib/Twig/Environment.php:270)
  at Twig_Environment->getTemplateClass('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/twig/twig/lib/Twig/Environment.php:350)
  at Twig_Environment->loadTemplate('@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/symfony/twig-bridge/Form/TwigRendererEngine.php:157)
  at Symfony\Bridge\Twig\Form\TwigRendererEngine->loadResourcesFromTheme('_filter_form', '@SonataMediaBundle/Form/media_widgets.html.twig')
     (vendor/symfony/twig-bridge/Form/TwigRendererEngine.php:111)
  at Symfony\Bridge\Twig\Form\TwigRendererEngine->loadResourceForBlockName('_filter_form', object(FormView), '_filter_errors')
     (vendor/symfony/form/AbstractRendererEngine.php:146)
  at Symfony\Component\Form\AbstractRendererEngine->loadResourceForBlockNameHierarchy('_filter_form', object(FormView), array('form_errors', '_filter_errors'), 1)
     (vendor/symfony/form/AbstractRendererEngine.php:84)
  at Symfony\Component\Form\AbstractRendererEngine->getResourceForBlockNameHierarchy(object(FormView), array('form_errors', '_filter_errors'), 1)
     (vendor/symfony/form/FormRenderer.php:208)
  at Symfony\Component\Form\FormRenderer->searchAndRenderBlock(object(FormView), 'errors')
     (var/cache/local/twig/b4/b41052ac663b03cdf8d7b2ab15f39a53adf1961b584240f149af40840fcc4bb7.php:914)

...
```

**Comment by kunicmarko20** [comment] 2018-04-05 18:31
The problem is that `@SonataMediaBundle` Should be `@SonataMedia` could you provide a PR?

**Comment by jordisala1991** [comment] 2018-04-05 18:57
The config is correct in docs: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/docs/reference/form.rst

What @kunicmarko20 said is basically the issue, but I think it should be changed on your code.

Closing for now.

**Closed by jordisala1991** 2018-04-05 18:57 UTC

**Comment by kunicmarko20** [comment] 2018-04-05 18:59
Oh, I thought docs were bad, great 😄

**Comment by phansys** [comment] 2018-04-05 19:12
Thank you, my config was wrong.
