### ISSUE TITLE
Overriding the MediaAdminController no longer works in 3.20.1

### ISSUE THREAD

**Issue by hithran** [sonata-project/SonataMediaBundle#1614] opened 2019-07-14 10:22 UTC
#### Sonata packages

```
sonata-project/admin-bundle              3.51.0 3.51.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.0  1.3.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.9.0  3.9.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.5.0  4.1.3  Symfony SonataFormatterBundle
sonata-project/media-bundle              3.20.1 3.20.1 Symfony SonataMediaBundle
sonata-project/seo-bundle                2.7.0  2.7.0  Symfony SonataSeoBundle
sonata-project/translation-bundle        2.4.2  2.4.2  SonataTranslationBundle
sonata-project/user-bundle               4.4.0  4.4.0  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/http-client           v4.3.2  v4.3.2  Symfony HttpClient component
symfony/http-client-contracts v1.1.5  v1.1.5  Generic abstractions related to HTTP clients
symfony/mime                  v4.3.2  v4.3.2  A library to manipulate MIME messages
symfony/monolog-bundle        v3.4.0  v3.4.0  Symfony MonologBundle
symfony/phpunit-bridge        v3.4.29 v4.3.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu         v1.11.0 v1.11.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype        v1.11.0 v1.11.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv        v1.11.0 v1.11.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu     v1.11.0 v1.11.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn     v1.11.0 v1.11.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring     v1.11.0 v1.11.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-util         v1.11.0 v1.11.0 Symfony utilities for portability of PHP codes
symfony/security-acl          v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle    v3.2.8  v3.2.8  Symfony SwiftmailerBundle
symfony/symfony               v3.4.29 v4.3.2  The Symfony PHP framework
```

#### PHP version

```
PHP 7.2.18 (cli) (built: May  8 2019 03:05:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

## Subject

I have a custom MediaAdminController (which is an extension of the MultiUploadController)  which I provide by setting the parameter sonata.media.admin.media.controller (As documented by the sonata-multiupload-bundle)
```
sonata.media.admin.media.controller: Application\Sonata\MediaBundle\Controller\MediaAdminController
```

This no longer works with 3.20.1, it does work with 3.20.0.
With PR https://github.com/sonata-project/SonataMediaBundle/pull/1603 all references to controllers were modernized, but if I revert the change on sonata.media.admin.media.controller my custom MediaAdminController is used again.

## Steps to reproduce
Install and configure the sonata media bundle and the sonata multiupload bundle

## Expected results
To see the multiupload form when adding an image

## Actual results
The single upload form is displayed

**Comment by greg0ire** [comment] 2019-07-14 10:31
@phansys can you please help?

**Comment by phansys** [comment] 2019-07-14 12:00
>@phansys can you please help?

Sure! I'll give it a try.

**Comment by phansys** [comment] 2019-07-14 14:17
I confirmed that the parameter "sonata.media.admin.media.controller" is properly respected in version `3.20.1`, allowing to use a custom controller.

I suggest you to check the behavior at "sonata-multiupload-bundle".

I'm closing the issue since it is not related to this bundle.
Thank you.

**Closed by phansys** 2019-07-14 14:17 UTC
Labels: bug, unconfirmed
