### ISSUE TITLE
No icons on buttons when creating new media

### ISSUE THREAD

**Issue by bigfoot90** [sonata-project/SonataMediaBundle#761] opened 2015-05-01 22:06 UTC
I'm using ```SonataAdminBundle 2.3``` and ```SonataMediaBundle 2.3```
There are not icons on buttons when creating an new media.
![schermata del 2015-05-01 23 57 16](https://cloud.githubusercontent.com/assets/4598274/7438096/f1bba1b2-f05e-11e4-9a64-b74a322964b8.png)

**Comment by AHWEBDEV** [comment] 2015-05-20 12:44
same here, this is due to base64 encoded images in src.

**Comment by lightglitch** [comment] 2015-05-20 23:24
The problem is that the core bundle always forces an image (https://github.com/sonata-project/SonataCoreBundle/blob/master/Model/Metadata.php#L60) and the class icon is ignored (https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/views/MediaAdmin/select_provider.html.twig#L32)
@rande a quick fix would be nice

**Comment by lightglitch** [comment] 2015-05-21 20:37
I's already fixed on master but not on stable. :(

**Comment by Hoannv** [comment] 2015-07-17 14:46
same issue: #778

**Comment by Soullivaneuh** [comment] 2015-07-22 08:36
> It's already fixed on master but not on stable. :(
> @rande Just added #769 can you make a quick stable release?

@lightglitch In which PR is already fixed on master? Could you cherry-pick it for a PR instead of creating a new one? Thanks.

**Comment by lightglitch** [comment] 2015-07-22 10:07
@Soullivaneuh the commit that fixes this is https://github.com/sonata-project/SonataMediaBundle/commit/01a776d86299e285cf91b34d9e2b6140db9c6e6d you can cherry-pick it and merge it.

**Comment by Soullivaneuh** [comment] 2015-07-22 11:11
@lightglitch done here: https://github.com/sonata-project/SonataMediaBundle/commit/7e10c0ea67f38583486e666694dfb08376ef1376

Stable release coming soon.

**Comment by Soullivaneuh** [comment] 2015-07-22 13:58
https://github.com/sonata-project/SonataMediaBundle/releases/tag/2.3.3

**Closed by Soullivaneuh** 2015-07-22 13:58 UTC
