### ISSUE TITLE
Add media from Gallery in IE 11 return file download create.json

### ISSUE THREAD

**Issue by cmlxmm** [sonata-project/SonataMediaBundle#808] opened 2015-07-04 11:15 UTC
Hello,

I'm using Sonata Admin together with Sonata Media Bundle. Everything works fine but today I've realized, that in Internet Explorer 11 on Win7 / 8.1 64bit there is an issue with creating Media item from Gallery admin.

In MediaAdmin everything works well. But if you will go to GalleryAdmin => e.g. opens existing gallery => press button add new (media to gallery) => on new row you will press Add new (save new media) => "pop-up" will show up to choose if you want to add file, document or another format => I'll choose Image => I'll choose the file to upload and click to button Create (this normaly in Chrome uploads the file and associate those file with Gallery. But in IE it will show up save as downloaded file dialog with file name create.json where the content is, e.g.: 

create.json
`{"result":"ok","objectId":"133"}`

The new Image is uploaded, Entity Media is saved, but not linked to Gallery and the pop-up window will stay open.

Do You have any idea how to fix it, apart to do not use IE ;-).

Thanks,

Martin

**Comment by core23** [comment] 2016-08-27 18:10
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by jordisala1991** [comment] 2018-03-29 07:01
Closing because this is related to AdminBundle and not to MediaBundle, here we dont have any script to control those popups.

If you still having this issue, please create it on the AdminBundle. Providing a javascript debug error would be nice. Test this first with latest Sonata versions please.

I did a fast search and I cant find related issues there and this could be the problematic script: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/Association/edit_many_script.html.twig

Even though I dont like jQuery a lot, it should be compatible with most browsers.

**Closed by jordisala1991** 2018-03-29 07:01 UTC
Labels: pending author
