### ISSUE TITLE
Form error with upload image

### ISSUE THREAD

**Issue by falexis77** [sonata-project/SonataMediaBundle#1145] opened 2016-11-21 11:27 UTC
### Environment
Linux 16.04 LTS
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.9.0   The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0   Symfony SonataBlockBundle
sonata-project/cache                     1.0.7   Cache library
sonata-project/classification-bundle     3.1.0   Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.1   Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2     Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2   Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.1   Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0   Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1   Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.2.4   Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0   Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0   Symfony SonataNotificationBundle
```
#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle                   v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle                   2.12.0  Symfony MonologBundle
symfony/phpunit-bridge                   v3.1.6  Symfony PHPUnit Bridge
symfony/polyfill-apcu                    v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu                v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.4.0  Symfony SwiftmailerBundle
symfony/symfony                          v3.1.6  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

 I want to link an image to an article. I generated the file ArticleAdmin with the sonata command
## **Entity Article**
/**
     * @var Media
     * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media", cascade={"persist","remove"})
     */
    private $image;

public function setImage(Media $image = null)
    {
        $this->image = $image;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

**ArticleAdmin**

$formMapper
            ->add('image', "sonata_media_type", array(
                'provider' => 'sonata.media.provider.image',
                'context'  => 'default',
                'label' => "image article",
                'required' => true
            ))
        ;

**config.yml**
`
sonata_media:
    class:
       media: Application\Sonata\MediaBundle\Entity\Media
       gallery: Application\Sonata\MediaBundle\Entity\Gallery
       gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                preview:   { width: 100, quality: 100}
                small: { width: 100 ,height: 64, quality: 70}
                big:   { width: 280 , height: 180, quality: 100}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

`

## Expected results

A image load on upload/media

## Actual results

   The form's view data is expected to be an instance of class Application\Sonata\MediaBundle\Entity\Media, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of Application\Sonata\MediaBundle\Entity\Media

**Comment by jordisala1991** [comment] 2018-03-29 06:37
This is the basic usage of the bundle I tried it and it works.

Closing because there is not enough information to reproduce the issue and it is very old. If you still having this issue I would recommend double checking that every sonata bundle is up to date and you configured it correctly.

If you still having this issue after that, please provide a full stack trace and we will reopen

**Closed by jordisala1991** 2018-03-29 06:37 UTC
