### ISSUE TITLE
Bottom checkbox for delete batch action removes all media instead of those in current category

### ISSUE THREAD

**Issue by halk** [sonata-project/SonataMediaBundle#1093] opened 2016-07-31 16:16 UTC
#### Sonata packages

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.4.0              The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1              Symfony SonataBlockBundle
sonata-project/cache                     dev-master f2f6be9 Cache library
sonata-project/cache-bundle              2.2.5              This bundle provides caching services
sonata-project/classification-bundle     3.1.0              Symfony SonataClassificationBundle
sonata-project/core-bundle               3.0.3              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.x-dev c5153d0    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.x-dev de6b7aa    Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5              Symfony Sonata / Integrate Doctrine ORM into the Sona...
sonata-project/easy-extends-bundle       2.x-dev 9c41573    Symfony SonataEasyExtendsBundle
sonata-project/exporter                  dev-master 474be8b Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1              Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP ...
sonata-project/intl-bundle               2.x-dev 27feb6b    Symfony SonataIntlBundle
sonata-project/media-bundle              3.1.0              Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0              Symfony SonataNotificationBundle
sonata-project/page-bundle               3.0.2              This bundle provides a Site and Page management throu...
sonata-project/seo-bundle                2.0.2              Symfony SonataSeoBundle
sonata-project/sonata-composer           dev-master 6ebe1f3
sonata-project/user-bundle               3.0.1              Symfony SonataUserBundle
```
#### Symfony packages

``` bash
$ composer show symfony/*
sonata-project/admin-bundle              3.4.0              The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1              Symfony SonataBlockBundle
sonata-project/cache                     dev-master f2f6be9 Cache library
sonata-project/cache-bundle              2.2.5              This bundle provides caching services
sonata-project/classification-bundle     3.1.0              Symfony SonataClassificationBundle
sonata-project/core-bundle               3.0.3              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.x-dev c5153d0    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.x-dev de6b7aa    Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5              Symfony Sonata / Integrate Doctrine ORM into the Sona...
sonata-project/easy-extends-bundle       2.x-dev 9c41573    Symfony SonataEasyExtendsBundle
sonata-project/exporter                  dev-master 474be8b Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1              Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP ...
sonata-project/intl-bundle               2.x-dev 27feb6b    Symfony SonataIntlBundle
sonata-project/media-bundle              3.1.0              Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0              Symfony SonataNotificationBundle
sonata-project/page-bundle               3.0.2              This bundle provides a Site and Page management throu...
sonata-project/seo-bundle                2.0.2              Symfony SonataSeoBundle
sonata-project/sonata-composer           dev-master 6ebe1f3
sonata-project/user-bundle               3.0.1              Symfony SonataUserBundle
```
#### PHP version

``` bash
$ php -v
PHP 5.6.24 (cli) (built: Jul 22 2016 02:41:22)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
## Subject

When filtering media by category in admin, the list shows only the items of that category. There is a checkbox at the bottom allowing the user to remove all media, confirming the number of items too (all elements(11)).

When performing the delete batch action, not only the media of the current category but all media in Sonata Media is removed. The number of items removed would also be higher than previously shown.

This led to data loss in a project of mine.
## Steps to reproduce

1) Create two categories
2) Upload an ideally different number of items to those categories
3) Select one of the categories
4) Check bottom checkbox "all elements", ensure dropdown right to it has "delete" selected
5) Click on OK
6) Confirm next page
## Expected results

Only items of the current category are removed.
## Actual results

All items are removed.

**Comment by core23** [comment] 2016-07-31 17:34
`All elements` means ALL elements. This is the expected behavior.

**Comment by greg0ire** [comment] 2016-07-31 20:47
@core23 : it says "all elements(11)", and suppresses a gazillion elements, so there might be a problem in fact, right?

**Comment by halk** [comment] 2016-08-01 09:14
Expected behaviour is either only remove ALL elements of the current category (as the number of items indicates that), or ALL elements regardless of category (then the number has to match all elements of Sonata Media). Latter is I think still a user experience setback in my opinion.

**Comment by greg0ire** [comment] 2016-08-01 09:18
So you experience the same problem with entities not in a category? With other child admit? I guess your admin is child of CategoryAdmin, right?

**Comment by halk** [comment] 2016-10-12 17:09
I was in a media category, which has certain number of elements. Clicked on All elements, it confirmed the number of items to be affected. Clicked remove. And it removed all elements in media, no item left, even those which are not in the category

**Comment by greg0ire** [comment] 2016-10-12 17:45
1. Do you experience the same problem with entities not in a category? 
2. Do you experience the same problem with other child admin?
3. I guess your admin (is it [BaseMediaAdmin](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Admin/BaseMediaAdmin.php)?) is a child of CategoryAdmin, or not? 

In your first post, under symfony packages, you put sonata packages…

**Comment by jordisala1991** [comment] 2018-03-17 12:17
This is related to https://github.com/sonata-project/SonataAdminBundle/issues/5030

IMO the admin-bundle issue is better since we can't do nothing from media-bundle. Closing this one for the moment to avoid duplicate issues. If you feel this is something we should fix on media-bundle and not on admin-bundle please ping me to reopen.

**Closed by jordisala1991** 2018-03-17 12:17 UTC
