### ISSUE TITLE
Error on Youtube and Dailymotion Provider can't add media

### ISSUE THREAD

**Issue by franckentien** [sonata-project/SonataMediaBundle#1397] opened 2018-02-20 11:11 UTC
#### Sonata packages

```
sonata-project/admin-bundle              3.31.1 = 3.31.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.0 = 3.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  = 2.0.1  Cache library
sonata-project/classification-bundle     3.6.1  = 3.6.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.9.0  = 3.9.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  = 2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  = 1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2  = 3.4.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdm...
sonata-project/easy-extends-bundle       2.5.0  = 2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  = 1.8.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.4.1  = 3.4.1  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.4.0  = 2.4.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.10.2 = 3.10.2 Symfony SonataMediaBundle
sonata-project/news-bundle               3.4.0  = 3.4.0  Symfony SonataNewsBundle
sonata-project/notification-bundle       3.3.1  = 3.3.1  Symfony SonataNotificationBundle
sonata-project/user-bundle               4.1.1  = 4.1.1  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.2 = v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.4 ~ v4.0.4 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 = v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 = v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 = v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 = v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 = v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 = v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 = v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 ~ v3.2.0 Symfony SwiftmailerBundle
symfony/symfony            v3.4.4 ~ v4.0.4 The Symfony PHP framework
```

#### PHP version

```
PHP 7.1.8 (cli) (built: Aug  1 2017 20:56:53) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject

On the most Basic project it's impossible to add Youtube and Dailymotion media.
Other Provider (Vimeo, Files, Picture) works perfectly.

## Steps to reproduce

Import the most basic project and add SonataBundle. 
Go on YouTube and get the url of the Video: https://www.youtube.com/watch?v=SGCYejWpcUE

Go to the Admin page on the page for add media: `/web/app_dev.php/admin/sonata/media/media/create?context=default&category=1&hide_context=0&provider=sonata.media.provider.youtube`

Past the ID of the video and click on add.

## Expected results

The result with Vimeo video. 

![image](https://user-images.githubusercontent.com/6872773/36420656-09f026d6-1636-11e8-87ce-b9136a94a21b.png)

## Actual results

![image](https://user-images.githubusercontent.com/6872773/36420590-d5367b70-1635-11e8-9782-3404e6139f6a.png)

on the profiler I get this errors:
![image](https://user-images.githubusercontent.com/6872773/36420737-423f116e-1636-11e8-8c49-1a294aea3a1a.png)

I thinks the error occur because it doesn't find the video on Youtube and can't get the name.

```
ConstraintViolation {#1704 ▼
  -message: "Cette valeur ne doit pas être nulle."
  -messageTemplate: "This value should not be null."
  -parameters: [▼
    "{{ value }}" => "null"
  ]
  -plural: null
  -root: Form {#1492 ▼
    name: "s5a8bf34c0a35c"
    type_class: "Symfony\Component\Form\Extension\Core\Type\FormType"
    data: Media {#1650 ▼
      #id: null
      #name: null
      #description: null
      #enabled: false
      #providerName: "sonata.media.provider.youtube"
      #providerStatus: 4
      #providerReference: "ffQM8ALVJV8"
      #providerMetadata: []
      #width: null
      #height: null
      #length: null
      #copyright: null
      #authorName: null
      #context: "default"
      #cdnIsFlushable: null
      #cdnFlushIdentifier: null
      #cdnFlushAt: null
      #cdnStatus: null
      #updatedAt: null
      #createdAt: null
      #binaryContent: "ffQM8ALVJV8"
      #previousProviderReference: null
      #contentType: null
      #size: null
      #galleryHasMedias: null
      #category: null
    }
  }
  -propertyPath: "data.name"
  -invalidValue: null
  -constraint: NotNull {#1535 …}
  -code: "ad32d13f-c3d4-423b-909a-857b961eb720"
  -cause: null
}
```

**Comment by kunicmarko20** [comment] 2018-02-21 21:29
fresh install of sonata admin + media:

```
sonata-project/admin-bundle              3.31.1 3.31.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.0 3.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.0  3.9.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2  3.4.2  Symfony Sonata / Integrate Doctrine ORM i...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/media-bundle              3.10.2 3.10.2 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.3.1  3.3.1  Symfony SonataNotificationBundle
sonata-project/user-bundle               4.1.1  4.1.1  Symfony SonataUserBundle
```

![screenshot from 2018-02-21 22-28-03](https://user-images.githubusercontent.com/13528674/36506342-9e8ab164-1756-11e8-9c1c-d6603135d33d.png)


As this is the second issue that you have and I can't reproduce, I am beginning to think that you did not configure something right. I just did fresh install and follow the docs.

**Comment by kunicmarko20** [comment] 2018-02-22 21:15
Cloned your https://github.com/franckentien/SampleSonataProject, followed How to use section. Opened admin and added youtube video without any problem:

![screenshot from 2018-02-22 22-00-44](https://user-images.githubusercontent.com/13528674/36564488-c5e84682-181d-11e8-99bc-db0ecbfd19a1.png)

**Comment by kunicmarko20** [comment] 2018-02-22 21:15
Can we close this as I can't reproduce it?

**Closed** 2018-02-22 22:33 UTC
Labels: bug, unconfirmed

**Comment by franckentien** [comment] 2018-10-24 09:30
Perfectly work on my production server thanks
