### ISSUE TITLE
Unable to find translatable as mapped property in entity

### ISSUE THREAD

**Issue by lukepass** [sonata-project/SonataMediaBundle#1377] opened 2018-01-23 09:44 UTC
Hello,
I am using Gedmo's Translatable extensions but it seems that I can't apply it to media fields:

```php
    /**
     * @var \Application\Sonata\MediaBundle\Entity\Media|null
     *
     * @ORM\ManyToOne(targetEntity="\Application\Sonata\MediaBundle\Entity\Media", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="video_1", referencedColumnName="id", onDelete="SET NULL")
     * @Gedmo\Translatable
     */
    protected $video1;
```

I receive this error:

```
  [Gedmo\Exception\InvalidMappingException]                                    
  Unable to find translatable [video1] as mapped property in entity - AppBund  
  le\Entity\Module                                                             
```

How can I do in order to translate media video? Thanks.

### Environment

Symfony 2.8

#### Sonata packages

```
$ composer show 'sonata-project/*'
sonata-project/admin-bundle              3.30.1 The missing Symfony Admin G...
sonata-project/block-bundle              3.10.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  Cache library
sonata-project/core-bundle               3.9.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extens...
sonata-project/doctrine-orm-admin-bundle 3.4.0  Symfony Sonata / Integrate ...
sonata-project/easy-extends-bundle       2.3.1  Symfony SonataEasyExtendsBu...
sonata-project/exporter                  1.8.0  Lightweight Exporter library
sonata-project/media-bundle              3.10.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.2.0  Symfony SonataNotificationB...
sonata-project/translation-bundle        2.2.0  SonataTranslationBundle
sonata-project/user-bundle               4.0.1  Symfony SonataUserBundle
```

#### PHP version

```
$ php -v
PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:26:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by jordisala1991** [comment] 2018-04-24 06:32
This is a question for StackOverflow, not a bug on Sonata. Unless you have detected some bug related to the usage of Gedmo.

Closing for now, if you think this is a bug on Sonata, please ping me to reopen

**Closed by jordisala1991** 2018-04-24 06:32 UTC
