### ISSUE TITLE
gallery_has_media was deleted after I add a new media to gallery

### ISSUE THREAD

**Issue by GregSong** [sonata-project/SonataMediaBundle#978] opened 2016-03-22 04:11 UTC
I'm trying to use gallery of media-bundle in project of my company. 
Currently media bundle version i'm using is 

```
"name": "sonata-project/media-bundle",
"version": "dev-master",
"source": {
"type": "git",
      "url": "https://github.com/sonata-project/SonataMediaBundle.git",
      "reference": "fd73a883209994ee5d787a8240574138547c8dd9"
},
```

I found that after I added a new media to gallery, the existing ones disappeared and I got doctrine log as below
![image](https://cloud.githubusercontent.com/assets/1024908/13941729/8fc21d52-f025-11e5-9abf-7d1a65a2b44e.png)
This is quite weird to me. 
After half day investigation, I found the questionable code in \Sonata\MediaBundle\Admin\GalleryAdmin as below:

```
public function preUpdate($gallery)
{
        // fix weird bug with setter object not being call
        $gallery->setGalleryHasMedias($gallery->getGalleryHasMedias());
}
```

setGalleryHasMedias will create a new ArrayCollection which causes Doctrine generate a drop statement to clean old records in gallery_has_media table.

I don't have knowledge about the purpose of that weird fix so I don't know whats to do next. 
Could you please have a look?

Thanks a lot

**Comment by pauliek** [comment] 2016-03-23 08:48
I can confirm that, same behaviour here, it's really nasty.

**Comment by clytemnestra** [comment] 2016-03-30 06:29
That's because Gallery has

```php
   public function setGalleryHasMedias($galleryHasMedias)
    {
        $this->galleryHasMedias = new ArrayCollection();

        foreach ($galleryHasMedias as $galleryHasMedia) {
            $this->addGalleryHasMedias($galleryHasMedia);
        }
    }
```
Shouldn't it delete the old ones and add new ones, then?

**Comment by GregSong** [comment] 2016-04-03 12:04
@clytemnestra ,I added media through gallery edit form. I think it should keep old ones when I add new. 
Maybe doctrine changed the behaviour when you assign a new collection to entity which cause a deletion now.

**Comment by Sahnie2013** [comment] 2017-03-24 10:26
I had the same issue in my new symfony project (symfony: 3.2.6, media-bundle: 3.5, doctrine-orm/dbal: 2.6.x-dev, doctrine-bundle: 1.6) as well. I couldn´t find any solution for this online and it seems there is no solution on this issue here. But i found a solution on my own and i will share this here. Yeah a year later, but i hope it will help someone.

The Problem here is, that doctrine use the "PersistentCollection" for entities, which already exists in the database. "ArrayCollection" is used for new entities. So whats the difference here?

As we can see in the opening post, doctrine runs first a DELETE-Statement on the gallery. After this its inserts the new entity AND updates the old ones (no insert for the old ones, because the old ones had already an id). But the old one is gone because of the DELETE-Statement. For the "PersistentCollection" doctrine didn´t use the DELETE-Statement.

If you inspect the "$galleryHasMedias" in the "setGalleryHasMedias" method, you will see that "$galleryHasMedias" is an instance of "PersistentCollection", if you have already entities in the database. The "setGalleryHasMedias" converts this "PeristentCollection" to an "ArrayCollection" and with this, you have the DELETE-Statement.

My Solution for this, is to overwrite the "setGalleryHasMedias" method in the "Application/Sonata/MediaBundle/Entity/Gallery.php" class (that would be generate through "php bin/console sonata:easy-extends:generate --dest=src SonataMediaBundle") in the "src"-Folder of your project. So you don´t have to change any code in the vendor.

The code is following (app/src/Application/Sonata/MediaBundle/Entity/Gallery.php):

`

    public function setGalleryHasMedias($galleryHasMedias)
    {
        if ($galleryHasMedias instanceof PersistentCollection) {
            //Set the gallery to each entity, because otherwise new entities wouldn´t saved with the gallery_id
            foreach ($galleryHasMedias as $galleryHasMedia) {
                $galleryHasMedia->setGallery($this);
            }

            $this->galleryHasMedias = $galleryHasMedias;
        } else {
            parent::setGalleryHasMedias($galleryHasMedias);
        }
    }
`

Since i add this to my gallery entity anything works fine. Adding new ones und update old ones in one go is not a problem any more. I hope this workaround helps someone.

**Comment by jordisala1991** [comment] 2018-03-18 19:53
This issue is the same as #1396 

Closing

**Closed by jordisala1991** 2018-03-18 19:53 UTC
Labels: bug, unconfirmed

**Comment by olelarssen** [comment] 2019-02-28 11:38
just override reorderGalleryHasMedia() method in your Gallery Entity

<?php

namespace App\Entity\SonataExtendedEntity;

use Sonata\MediaBundle\Entity\BaseGallery as BaseGallery;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="gallery")
 * @ORM\HasLifecycleCallbacks()
 */
class Gallery extends BaseGallery
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Reorders $galleryHasMedia items based on their position.
     */
    public function reorderGalleryHasMedia()
    {
       //
    }
}
