### ISSUE TITLE
Orphan Removal with doctrine fails

### ISSUE THREAD

**Issue by Floyd25** [sonata-project/SonataMediaBundle#777] opened 2015-05-31 16:11 UTC
It seems like orphan removal with doctrine is not supported correctly:

/**
     \* @var Media
     \* @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media", orphanRemoval=true)
     \* @ORM\JoinColumn(name="group_logo", referencedColumnName="id", nullable=true)
     \* @Assert\Valid
     */
    protected $groupLogo = NULL;

When Updating my entity with a new Media, I receive the following error:

CRITICAL - Uncaught PHP Exception RuntimeException: "Could not remove the "grouplogo/0001/01/" key." at <...>/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php line 172
Context: {"exception":"Object(RuntimeException)"} 

So I have to manually delete Media-Objects when an entity changes?

**Comment by core23** [comment] 2016-08-27 17:10
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by mgrundkoetter** [comment] 2016-12-05 15:31
I can confirm this issue. SonataMediaBundle 3.3.0 php7fpm and nginx on debian. Image was uploaded with SonataAdmin and when the entity is to be deleted (where the image is attached), the error occurs. Default file permission after upload is 644 for the file in question. User is sftp user, group is "users". php5fpm is run as www-data

**Comment by greg0ire** [comment] 2016-12-05 15:35
Can you provide a stack trace? And a link to the relevant Gaufrette piece of code?

**Comment by mgrundkoetter** [comment] 2016-12-05 15:40
Not a full stack trace, but the symfony log line: 

[2016-12-04 19:42:47] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Could not remove the "profiles/0001/04/ee5dac76132b1e1e6feca307a4f4454d4ffecc3c.png" key." at /var/www/html/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php line 170 {"exception":"[object] (RuntimeException(code: 0): Could not remove the \"profiles/0001/04/ee5dac76132b1e1e6feca307a4f4454d4ffecc3c.png\" key. at /var/www/html/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php:170)"} []

I guess it is just a misconfiguration of the webserver/php stack. I wonder why the files have <myuser>:users instead of <myuser>:www-data or www-data:users permission as they were uploaded with the SonataAdmin bundle.

**Comment by greg0ire** [comment] 2016-12-05 15:41
Please provide a full stack trace. If you are in the http context, use the symfony profiler, there is a form to find previous requests and the corresponding logs (and stack traces, I think)

**Comment by jordisala1991** [comment] 2018-03-01 22:35
This seems to be related to a bad configuration of permissions and users. Closing. If this is still relevant, ping me to reopen

**Closed by jordisala1991** 2018-03-01 22:35 UTC
Labels: pending author
